sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vivche/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true vivche/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-842323604083'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
